import {
  FiHeadphones,
  FiSmartphone,
  FiWatch,
  FiCamera,
  FiCpu,
  FiSpeaker,
} from "react-icons/fi";

export const orbitProducts = [
  {
    id: 1,
    image: "/3.png",
    title: "heroProductOnePlus15Title",
    description: "heroProductOnePlus15Description",
    subtitle: "heroProductOnePlus15Subtitle",
    cat: {
      id: 1,
      title: "categorySmartphones",
      products: "categoryProducts",
      image: "/cat.jpg",
    },
    icon: FiSmartphone,
    active: true,
    angle: 0,
    price: "799",
    properties: [
      "heroProductOnePlus15PropertySnapdragon9Gen4",
      "heroProductOnePlus15Property5GReady",
      "heroProductOnePlus15Property4KVideo",
      "heroProductOnePlus15PropertyIP68",
    ],
    color: "#EF4444"
  },
  {
    id: 2,
    image: "/2.png",
    title: "heroProductAirPodsPro3Title",
    description: "heroProductAirPodsPro3Description",
    subtitle: "heroProductAirPodsPro3Subtitle",
    cat: {
      id: 1,
      title: "categorySmartphones",
      products: "categoryProducts",
      image: "/cat.jpg",
    },
    icon: FiHeadphones,
    active: false,
    angle: 45,
    price: "1199",
    properties: [
      "heroProductAirPodsPro3PropertySnapdragon9Gen3",
      "heroProductAirPodsPro3Property5GReady",
      "heroProductAirPodsPro3Property4KVideo",
      "heroProductAirPodsPro3PropertyIP68",
    ],
    color: "#8B5CF6"
  },
  {
    id: 3,
    image: "/3.png",
    title: "heroProductSmartWatchTitle",
    description: "heroProductSmartWatchDescription",
    subtitle: "heroProductSmartWatchSubtitle",
    cat: {
      id: 1,
      title: "categorySmartphones",
      products: "categoryProducts",
      image: "/cat.jpg",
    },
    icon: FiWatch,
    active: false,
    angle: 90,
    price: "649",
    properties: [
      "heroProductSmartWatchPropertySnapdragon9Gen2",
      "heroProductSmartWatchProperty5GReady",
      "heroProductSmartWatchProperty4KVideo",
      "heroProductSmartWatchPropertyIP68",
    ],
    color: "#D4D4D4"
  },
  {
    id: 4,
    image: "/4.png",
    title: "heroProduct4KCameraTitle",
    description: "heroProduct4KCameraDescription",
    subtitle: "heroProduct4KCameraSubtitle",
    cat: {
      id: 1,
      title: "categorySmartphones",
      products: "categoryProducts",
      image: "/cat.jpg",
    },
    icon: FiCamera,
    active: false,
    angle: 135,
    price: "999",
    properties: [
      "heroProduct4KCameraPropertyTensor5G",
      "heroProduct4KCameraProperty5GReady",
      "heroProduct4KCameraProperty4KVideo",
      "heroProduct4KCameraPropertyIP68",
    ],
    color: "#06B6D4"
  },
  {
    id: 5,
    image: "/5.png",
    title: "heroProductSmartSpeakerTitle",
    description: "heroProductSmartSpeakerDescription",
    subtitle: "heroProductSmartSpeakerSubtitle",
    cat: {
      id: 1,
      title: "categorySmartphones",
      products: "categoryProducts",
      image: "/cat.jpg",
    },
    icon: FiSpeaker,
    active: false,
    angle: 180,
    price: "899",
    properties: [
      "heroProductSmartSpeakerPropertySnapdragon9Gen4",
      "heroProductSmartSpeakerProperty5GReady",
      "heroProductSmartSpeakerProperty4KVideo",
      "heroProductSmartSpeakerPropertyIP68",
    ],
    color: "#F97316"
  },
  {
    id: 6,
    image: "/6.png",
    title: "heroProductTensorG5Title",
    description: "heroProductTensorG5Description",
    subtitle: "heroProductTensorG5Subtitle",
    cat: {
      id: 1,
      title: "categorySmartphones",
      products: "categoryProducts",
      image: "/cat.jpg",
    },
    icon: FiCpu,
    active: false,
    angle: 225,
    price: "1299",
    properties: [
      "heroProductTensorG5PropertyA19ProChip",
      "heroProductTensorG5Property5GReady",
      "heroProductTensorG5Property4KVideo",
      "heroProductTensorG5PropertyIP68",
    ],
    color: "#3B82F6"
  },
];

export const categories = [
  {
    id: 1,
    title: "categorySmartphones",
    products: "categoryProducts",
    image: "/cat.jpg",
  },
  {
    id: 2,
    title: "categoryGaming",
    products: "categoryProducts",
    image: "/cat.jpg",
  },
  {
    id: 3,
    title: "categoryLaptops",
    products: "categoryProducts",
    image: "/cat.jpg",
  },
  {
    id: 4,
    title: "categoryAudio",
    products: "categoryProducts",
    image: "/cat.jpg",
  },
  {
    id: 5,
    title: "categorySmartHome",
    products: "categoryProducts",
    image: "/cat.jpg",
  },
  {
    id: 6,
    title: "categoryGaming",
    products: "categoryProducts",
    image: "/cat.jpg",
  },
  {
    id: 7,
    title: "categoryLaptops",
    products: "categoryProducts",
    image: "/cat.jpg",
  },
  {
    id: 8,
    title: "categoryGaming",
    products: "categoryProducts",
    image: "/cat.jpg",
  },
  {
    id: 9,
    title: "categoryLaptops",
    products: "categoryProducts",
    image: "/cat.jpg",
  },
];

export const products = [
  {
    id: 1,
    title: "flashSaleProductEarbuds",
    image: "/earbuds.jpg",
    price: 400,
    oldPrice: 550,
    rate: 5.0,
    discount: 25,
    cat: {
      id: 1,
      title: "categorySmartphones",
      products: "categoryProducts",
      image: "/cat.jpg",
    },
  },
  {
    id: 2,
    title: "flashSaleProductHeadphones",
    image: "/earbuds.jpg",
    price: 250,
    oldPrice: 300,
    rate: 4.5,
    discount: 17,
    cat: {
      id: 1,
      title: "categorySmartphones",
      products: "categoryProducts",
      image: "/cat.jpg",
    },
  },
  {
    id: 3,
    title: "flashSaleProductSpeaker",
    image: "/earbuds.jpg",
    price: 150,
    oldPrice: 180,
    rate: 3.8,
    discount: 16,
    cat: {
      id: 1,
      title: "categorySmartphones",
      products: "categoryProducts",
      image: "/cat.jpg",
    },
  },
  {
    id: 4,
    title: "flashSaleProductTravelHeadphones",
    image: "/earbuds.jpg",
    price: 350,
    oldPrice: 420,
    rate: 4.2,
    discount: 17,
    cat: {
      id: 1,
      title: "categorySmartphones",
      products: "categoryProducts",
      image: "/cat.jpg",
    },
  },
  {
    id: 5,
    title: "flashSaleProductSmartWatch",
    image: "/earbuds.jpg",
    price: 650,
    oldPrice: 800,
    rate: 4.7,
    discount: 19,
    cat: {
      id: 1,
      title: "categorySmartphones",
      products: "categoryProducts",
      image: "/cat.jpg",
    },
  },
  {
    id: 6,
    title: "flashSaleProductWirelessCharger",
    image: "/earbuds.jpg",
    price: 180,
    oldPrice: 240,
    rate: 4.3,
    discount: 25,
    cat: {
      id: 1,
      title: "categorySmartphones",
      products: "categoryProducts",
      image: "/cat.jpg",
    },
  },
  {
    id: 7,
    title: "flashSaleProductPowerBank",
    image: "/earbuds.jpg",
    price: 300,
    oldPrice: 380,
    rate: 4.6,
    discount: 21,
    cat: {
      id: 1,
      title: "categorySmartphones",
      products: "categoryProducts",
      image: "/cat.jpg",
    },
  },
  {
    id: 8,
    title: "flashSaleProductGamingMouse",
    image: "/earbuds.jpg",
    price: 275,
    oldPrice: 350,
    rate: 4.8,
    discount: 21,
    cat: {
      id: 1,
      title: "categorySmartphones",
      products: "categoryProducts",
      image: "/cat.jpg",
    },
  },
  {
    id: 9,
    title: "flashSaleProductKeyboard",
    image: "/earbuds.jpg",
    price: 450,
    oldPrice: 550,
    rate: 4.4,
    discount: 18,
    cat: {
      id: 1,
      title: "categorySmartphones",
      products: "categoryProducts",
      image: "/cat.jpg",
    },
  },
  {
    id: 10,
    title: "flashSaleProductBluetoothSpeaker",
    image: "/earbuds.jpg",
    price: 320,
    oldPrice: 400,
    rate: 4.1,
    discount: 20,
    cat: {
      id: 1,
      title: "categorySmartphones",
      products: "categoryProducts",
      image: "/cat.jpg",
    },
  },
  {
    id: 11,
    title: "flashSaleProductUSBHub",
    image: "/earbuds.jpg",
    price: 200,
    oldPrice: 260,
    rate: 4.0,
    discount: 23,
    cat: {
      id: 1,
      title: "categorySmartphones",
      products: "categoryProducts",
      image: "/cat.jpg",
    },
  },
  {
    id: 12,
    title: "flashSaleProductWebcam",
    image: "/earbuds.jpg",
    price: 500,
    oldPrice: 650,
    rate: 4.6,
    discount: 23,
    cat: {
      id: 1,
      title: "categorySmartphones",
      products: "categoryProducts",
      image: "/cat.jpg",
    },
  },
];