export const products = [
  {
    id: 1,
    title: "flashSaleProductEarbuds",
    image: "/earbuds.jpg",
    price: 400,
    oldPrice: 550,
    rate: 5.0,
    discount: 25,
  },
  {
    id: 2,
    title: "flashSaleProductHeadphones",
    image: "/earbuds.jpg",
    price: 250,
    oldPrice: 300,
    rate: 4.5,
    discount: 17,
  },
  {
    id: 3,
    title: "flashSaleProductSpeaker",
    image: "/earbuds.jpg",
    price: 150,
    oldPrice: 180,
    rate: 3.8,
    discount: 16,
  },
  {
    id: 4,
    title: "flashSaleProductTravelHeadphones",
    image: "/earbuds.jpg",
    price: 350,
    oldPrice: 420,
    rate: 4.2,
    discount: 17,
  },
  {
    id: 5,
    title: "flashSaleProductSmartWatch",
    image: "/earbuds.jpg",
    price: 650,
    oldPrice: 800,
    rate: 4.7,
    discount: 19,
  },
  {
    id: 6,
    title: "flashSaleProductWirelessCharger",
    image: "/earbuds.jpg",
    price: 180,
    oldPrice: 240,
    rate: 4.3,
    discount: 25,
  },
  {
    id: 7,
    title: "flashSaleProductPowerBank",
    image: "/earbuds.jpg",
    price: 300,
    oldPrice: 380,
    rate: 4.6,
    discount: 21,
  },
  {
    id: 8,
    title: "flashSaleProductGamingMouse",
    image: "/earbuds.jpg",
    price: 275,
    oldPrice: 350,
    rate: 4.8,
    discount: 21,
  },
  {
    id: 9,
    title: "flashSaleProductKeyboard",
    image: "/earbuds.jpg",
    price: 450,
    oldPrice: 550,
    rate: 4.4,
    discount: 18,
  },
  {
    id: 10,
    title: "flashSaleProductBluetoothSpeaker",
    image: "/earbuds.jpg",
    price: 320,
    oldPrice: 400,
    rate: 4.1,
    discount: 20,
  },
  {
    id: 11,
    title: "flashSaleProductUSBHub",
    image: "/earbuds.jpg",
    price: 200,
    oldPrice: 260,
    rate: 4.0,
    discount: 23,
  },
  {
    id: 12,
    title: "flashSaleProductWebcam",
    image: "/earbuds.jpg",
    price: 500,
    oldPrice: 650,
    rate: 4.6,
    discount: 23,
  },
];