import type { Metadata } from "next";
import { Poppins, Readex_Pro } from "next/font/google";
import "./globals.css";
import { getLocale, getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import MainProvider from "@/rtk/MainProvider";
import { cookies } from "next/headers";
import ResponsiveToaster from "@/components/ResponsiveToaster/ResponsiveToaster";

export const metadata: Metadata = {
  title: "KM Store",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  const token = (await cookies()).get("token")?.value || null;

  return (
    <html lang={locale} dir={locale == "ar" ? "rtl" : "ltr"} className="dark">
      <body>
        <ResponsiveToaster />
        <NextIntlClientProvider messages={messages}>
          <MainProvider
            lang={locale}
            token={token}
          >
            {children}
          </MainProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
